/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 goalKeeper.gltf 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useCharacterAnimation } from "@/contexts/CharacterAnimation";
import * as THREE from "three";
import { goal_keeper_positions } from "@/utils/goalKeeperPositions.js";
import { GAME_TIMING } from "@/utils/gameTiming";

export function Goalkeeper_1(props) {
  const { action, type, animationTime, playing } = props;
  const group = useRef();

  const { nodes, materials, animations } = useGLTF(
    "../models/goalkeeper/goalkeeper_1.glb"
  );
  const { actions } = useAnimations(animations, group);
  const { animationIndex } = useCharacterAnimation();
  const finishedHandlerRef = useRef(null);

  const startMovement = (fadeDuration = 0.3) => {
    const animation = actions[goal_keeper_positions[type].idle.animation];
    if (!animation) return;
    Object.values(actions).forEach((a) => {
      if (a !== animation) a.stop();
    });
    animation.setLoop(THREE.LoopRepeat);
    animation.reset();
    if (fadeDuration > 0) animation.fadeIn(fadeDuration);
    animation.play();
  };

  const stopMovement = (name) => {
    const animation = actions[goal_keeper_positions[type][name].animation];
    if (animation) animation.stop();
  };

  const handleKeep = () => {
    if (!playing) {
      startMovement();
      return;
    }
    const animation = actions[goal_keeper_positions[type][action].animation];
    if (!animation) return;
    stopMovement("idle");
    animation.reset();
    animation.setLoop(THREE.LoopOnce);
    animation.clampWhenFinished = true;
    animation.fadeIn(0.12);
    animation.play();
    const mixer = animation.getMixer();
    const onFinished = () => {
      mixer.removeEventListener("finished", onFinished);
      if (finishedHandlerRef.current === onFinished) {
        finishedHandlerRef.current = null;
      }
      startMovement(0.3);
    };
    if (finishedHandlerRef.current) {
      mixer.removeEventListener("finished", finishedHandlerRef.current);
    }
    finishedHandlerRef.current = onFinished;
    mixer.addEventListener("finished", onFinished);
  };

  useEffect(() => {
    if (
      Object.keys(actions).length === 0 ||
      !actions[goal_keeper_positions[type].idle.animation]
    ) {
      return;
    }

    if (animationIndex === 0) {
      Object.values(actions).forEach((a) => a.stop());
      startMovement();
      return;
    }

    if (animationIndex === 1) {
      const timer = setTimeout(() => {
        stopMovement("idle");
        handleKeep();
      }, Math.max(0, animationTime * 1000 - GAME_TIMING.keeperDiveOffset));
      return () => clearTimeout(timer);
    }
  }, [animationIndex, actions, action, type, animationTime]);

  return (
    <group ref={group} {...props} dispose={null} receiveShadow castShadow>
      <group name="Scene">
        <group
          name="idle"
          rotation={goal_keeper_positions[type].idle.rotation}
          position={goal_keeper_positions[type].idle.position}
          scale={0.01}
        >
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="brown_2__Body"
            geometry={nodes.brown_2__Body.geometry}
            material={materials.body1}
            skeleton={nodes.brown_2__Body.skeleton}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="brown_2_Eyes"
            geometry={nodes.brown_2_Eyes.geometry}
            material={materials.Wolf3D_Eye3}
            skeleton={nodes.brown_2_Eyes.skeleton}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="brown_2_hair"
            geometry={nodes.brown_2_hair.geometry}
            material={materials.Wolf3D_Hair1}
            skeleton={nodes.brown_2_hair.skeleton}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="brown_2_Head"
            geometry={nodes.brown_2_Head.geometry}
            material={materials.head1}
            skeleton={nodes.brown_2_Head.skeleton}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="brown_2_pants"
            geometry={nodes.brown_2_pants.geometry}
            material={materials.pantaloneta5}
            skeleton={nodes.brown_2_pants.skeleton}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="brown_2_shirt"
            geometry={nodes.brown_2_shirt.geometry}
            material={materials.shirt6}
            skeleton={nodes.brown_2_shirt.skeleton}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="brown_2_shoes"
            geometry={nodes.brown_2_shoes.geometry}
            material={materials.shoes5}
            skeleton={nodes.brown_2_shoes.skeleton}
            castShadow
            receiveShadow
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/goalkeeper/goalkeeper_1.glb");
