/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 models/ball/ball.gltf 
*/

import React, { useEffect, useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useSphereCollaider } from "../Collaiders/collaiders";
import { useCharacterAnimation } from "@/contexts/CharacterAnimation";
import { trayectory_forces } from "@/utils/trayectory_forces";
import { GAME_TIMING } from "@/utils/gameTiming";
import { sounds } from "../sounds/sounds";
import { useAuth } from "../providers/auth-provider";
import * as THREE from "three";
import { useTexture, Trail, Sparkles } from "@react-three/drei";

const IS_MOBILE = typeof window !== "undefined" && window.innerWidth < 768;

export function Ball(props) {
  const { data: user } = useAuth();
  const {
    position,
    animationTime,
    direction,
    force,
    onAttempt,
    onKick,
    playing,
    slowMo,
    powerup,
  } = props;
  const { animationIndex } = useCharacterAnimation();

  const { sphereCollaider, sphereCollaiderAPI } = useSphereCollaider({
    scale: [0.15, 0.15, 0.15],
    args: [0.15],
    position: trayectory_forces[position].ball_position,
    rotation: [0, 0, 0],
    mass: 0.2,
    type: "Dynamic",
    material: {
      friction: 0.6,
      restitution: 0.7,
    },
    name: "ball",
    onCollide: (e) => {},
  });

  const impactRingRef = useRef();
  const impactFlashRef = useRef();
  const sparklesRef = useRef();
  const impactUntilRef = useRef(0);
  const squashRef = useRef(0);
  const slowMoRef = useRef(false);
  useEffect(() => {
    slowMoRef.current = slowMo;
  }, [slowMo]);

  const restartBall = () => {
    sphereCollaiderAPI.velocity.set(0, 0, 0);
    sphereCollaiderAPI.angularVelocity.set(0, 0, 0);
    sphereCollaiderAPI.position.set(
      trayectory_forces[position].ball_position[0],
      trayectory_forces[position].ball_position[1],
      trayectory_forces[position].ball_position[2]
    );
    impactUntilRef.current = 0;
    squashRef.current = 0;
    if (sphereCollaider.current) sphereCollaider.current.scale.set(1, 1, 1);
    if (impactRingRef.current) impactRingRef.current.visible = false;
    if (impactFlashRef.current) impactFlashRef.current.visible = false;
    if (sparklesRef.current) sparklesRef.current.visible = false;
  };

  useEffect(() => {
    restartBall();
  }, [position]);

  const shoot = () => {
    if (!playing) return;
    const directionForces = trayectory_forces[position][direction];
    if (!directionForces || !directionForces[force]) return;
    const force_ = directionForces[force];
    sounds.kick_1.play();

    const now = performance.now();
    impactUntilRef.current = now + GAME_TIMING.impactDuration;
    squashRef.current = 1;
    if (impactRingRef.current) impactRingRef.current.visible = true;
    if (impactFlashRef.current) impactFlashRef.current.visible = true;
    if (sparklesRef.current) sparklesRef.current.visible = true;

    const s = GAME_TIMING.spin;
    const left = typeof direction === "string" && direction.includes("left");
    const right = typeof direction === "string" && direction.includes("right");
    const side = left ? 1 : right ? -1 : 0;
    sphereCollaiderAPI.angularVelocity.set(
      s.roll,
      s.lateral * side,
      0
    );

    sphereCollaiderAPI.applyForce(force_, [0, 0, 0]);
    if (typeof onKick === "function") onKick();
    if (typeof onAttempt === "function") onAttempt();
  };

  useEffect(() => {
    if (animationIndex !== 1) return;
    const delay = GAME_TIMING.shootDelayByPlayer[user.avatar_id] ?? 500;
    const timeout = setTimeout(() => {
      shoot();
    }, Math.max(0, animationTime * 1000 - delay));
    return () => clearTimeout(timeout);
  }, [animationIndex, animationTime]);

  useFrame(() => {
    const v = sphereCollaiderAPI.velocity;
    const speed = Math.sqrt(v.x * v.x + v.y * v.y + v.z * v.z);

    if (impactUntilRef.current > 0) {
      const remaining = impactUntilRef.current - performance.now();
      if (remaining <= 0) {
        impactUntilRef.current = 0;
        if (impactRingRef.current) impactRingRef.current.visible = false;
        if (impactFlashRef.current) impactFlashRef.current.visible = false;
        if (sparklesRef.current) sparklesRef.current.visible = false;
      } else {
        const t = 1 - remaining / GAME_TIMING.impactDuration;
        if (impactRingRef.current) {
          impactRingRef.current.scale.setScalar(1 + t * 2.5);
          impactRingRef.current.material.opacity = 0.9 * (1 - t);
        }
        if (impactFlashRef.current) {
          impactFlashRef.current.scale.setScalar(1 + t * 2);
          impactFlashRef.current.material.opacity = 0.7 * (1 - t);
        }
      }
    }

    if (squashRef.current > 0) {
      squashRef.current = Math.max(0, squashRef.current - 0.12);
      if (sphereCollaider.current) {
        const sq = squashRef.current;
        sphereCollaider.current.scale.set(
          1 + sq * 0.22,
          1 - sq * 0.25,
          1 + sq * 0.22
        );
      }
    }

    if (slowMoRef.current && speed > 0.5) {
      const d = 1 - GAME_TIMING.slowMoDrag;
      sphereCollaiderAPI.velocity.set(v.x * d, v.y * d, v.z * d);
    }

    if (speed > 1) {
      const w = sphereCollaiderAPI.angularVelocity;
      const ws = w.x * w.x + w.y * w.y + w.z * w.z;
      if (ws > 0.01) {
        const k = GAME_TIMING.magnus * (IS_MOBILE ? 0.7 : 1);
        const fx = (w.y * v.z - w.z * v.y) * k;
        const fy = (w.z * v.x - w.x * v.z) * k;
        const fz = (w.x * v.y - w.y * v.x) * k;
        sphereCollaiderAPI.applyForce([fx, fy, fz], [0, 0, 0]);
      }
    }
  });

  // texture
  const [texture, normal, roughness] = useTexture([
    "/ball_texture/ball_albedo.jpg",
    "/ball_texture/ball_normal.jpg",
    "/ball_texture/ball_roughness.jpg",
  ]);

  return (
    <group dispose={null}>
      <mesh
        ref={sphereCollaider}
        receiveShadow={true}
        castShadow={true}
      >
        <sphereGeometry args={[0.15, 10, 10]} />
        <meshStandardMaterial
          map={texture}
          normalMap={normal}
          roughnessMap={roughness}
          roughness={0.5}
          normalScale={new THREE.Vector2(5, 5)}
        />
        {powerup && (
          <mesh scale={1.5}>
            <sphereGeometry args={[0.15, 10, 10]} />
            <meshBasicMaterial
              color="#ffd700"
              transparent
              opacity={0.3}
              blending={THREE.AdditiveBlending}
              depthWrite={false}
            />
          </mesh>
        )}
        <mesh ref={impactRingRef} visible={false}>
          <ringGeometry args={[0.2, 0.32, 32]} />
          <meshBasicMaterial
            color="#00ffd5"
            transparent
            opacity={0.9}
            side={THREE.DoubleSide}
          />
        </mesh>
        <mesh ref={impactFlashRef} visible={false}>
          <sphereGeometry args={[0.28, 10, 10]} />
          <meshBasicMaterial
            color="#ffffff"
            transparent
            opacity={0.7}
            blending={THREE.AdditiveBlending}
            depthWrite={false}
          />
        </mesh>
        <Sparkles
          ref={sparklesRef}
          count={IS_MOBILE ? 6 : 12}
          scale={0.3}
          size={2}
          speed={0.4}
          color="#00ffd5"
          visible={false}
        />
      </mesh>
      <Trail
        width={IS_MOBILE ? 0.06 : 0.12}
        length={IS_MOBILE ? 3 : 6}
        decay={2}
        color="#00ffd5"
        attenuation={(t) => t}
        target={sphereCollaider}
      />
    </group>
  );
}
