/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 models/ball/ball.gltf 
*/

import React, { useEffect, useLayoutEffect, useRef, useState } from "react";
import { useSphereCollaider } from "../Collaiders/collaiders";
import { useCharacterAnimation } from "@/contexts/CharacterAnimation";
import { trayectory_forces } from "@/utils/trayectory_forces";
import { sounds } from "../sounds/sounds";
import { useAuth } from "../providers/auth-provider";
import * as THREE from "three";
import { useTexture } from "@react-three/drei";

const playersDelay = {
  1: 600,
  2: 500,
  3: 500,
  4: 700,
  5: 500,
  6: 500,
};

export function Ball(props) {
  const { data: user } = useAuth();
  const { position, animationTime, direction, force, attemptShoot, playing } =
    props;
  const { animationIndex, setAnimationIndex } = useCharacterAnimation();

  const { sphereCollaider, sphereCollaiderAPI } = useSphereCollaider({
    scale: [0.15, 0.15, 0.15],
    args: [0.15],
    position: trayectory_forces[position].ball_position,
    rotation: [0, 0, 0],
    mass: 0.2,
    type: "Dynamic",
    material: {
      friction: 0.5,
      restitution: 0.9,
    },
    name: "ball",
    onCollide: (e) => {},
  });

  const restartBall = () => {
    sphereCollaiderAPI.velocity.set(0, 0, 0);
    sphereCollaiderAPI.angularVelocity.set(0, 0, 0);
    sphereCollaiderAPI.position.set(
      trayectory_forces[position].ball_position[0],
      trayectory_forces[position].ball_position[1],
      trayectory_forces[position].ball_position[2]
    );
    setAnimationIndex(0);
  };

  useEffect(() => {
    restartBall();
  }, [position]);

  const shoot = () => {
    if (playing) {
      const force_ = trayectory_forces[position][direction][force];
      sounds.kick_1.play();
      sphereCollaiderAPI.applyForce(force_, [0, 0, 0]);
      attemptShoot(3, restartBall);
    }
  };

  useEffect(() => {
    const delay = playersDelay[user.avatar_id];
    switch (animationIndex) {
      case 1:
        setTimeout(() => {
          shoot();
        }, animationTime * 1000 - delay);
        break;
      default:
        break;
    }
  }, [animationIndex]);

  // texture
  const [texture, normal, roughness] = useTexture([
    "/ball_texture/ball_albedo.jpg",
    "/ball_texture/ball_normal.jpg",
    "/ball_texture/ball_roughness.jpg",
  ]);

  return (
    <group dispose={null}>
      <mesh ref={sphereCollaider} receiveShadow={true} castShadow={true}>
        <sphereGeometry args={[0.15, 10, 10]} />
        <meshStandardMaterial
          map={texture}
          normalMap={normal}
          roughnessMap={roughness}
          roughness={0.5}
          normalScale={new THREE.Vector2(5, 5)}
        />
      </mesh>
    </group>
  );
}
