/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 arco.gltf 
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import {
  BoxCollaider,
  CylinderCollaider,
  PlaneCollider,
} from "../Collaiders/collaiders";
import { goal_keeper_positions } from "@/utils/goalKeeperPositions";
import { sounds } from "../sounds/sounds";
import { useBox } from "@react-three/cannon";

const planes = [
  // [position, rotation, size]
  [
    [0, 1.5, -2],
    [0, 0, 0],
    [7.6, 2.8, 1],
    (e) => {
      // stop ball
    },
  ], // Fondo
  [
    [-3.7, 1.5, -0.7],
    [0, Math.PI / 2, 0],
    [2.5, 2.8, 0.1],
  ], // Lado izquierdo
  [
    [3.7, 1.5, -0.7],
    [0, -Math.PI / 2, 0],
    [2.5, 2.8, 0.1],
  ], // Lado derecho
  [
    [0, 3, -0.7],
    [-Math.PI / 2, 0, 0],
    [7.6, 2.3, 0.1],
  ], // Parte superior
  [
    [0, 0, -0.9],
    [-Math.PI / 2, 0, 0],
    [7.4, 2, 0.1],
  ],
];

export function Goal(props) {
  const { shootType, keepPosition, setGoals, onGoal, onSave, onPost } = props;
  const goalRef = useRef(false);
  const handleGoal = (e) => {
    if (!goalRef.current) {
      goalRef.current = true;
      sounds.goal.play();
      sounds.goal_stadium.play();
      setGoals((prev) => prev + 1);
      if (typeof onGoal === "function") onGoal();
    }
  };
  const [ref, api] = useBox(() => ({
    args: [7.4, 2.6, 0.1],
    position: [0, 1.3, -0.6],
    isTrigger: true,
    onCollide: (e) => {
      handleGoal();
    },
  }));

  useEffect(() => {
    goalRef.current = false;
  }, [shootType]);

  return (
    <group>
      <group {...props} dispose={null}>
        <BoxCollaider
          args={[1.2, 2.2, 0.4]}
          position={
            goal_keeper_positions[shootType][keepPosition]?.collider_position
          }
          rotation={
            goal_keeper_positions[shootType][keepPosition]?.collider_rotation
          }
          mass={1}
          type="Static"
          material={{ restitution: 0.1, friction: 0.9 }}
          name="keeper_goal_area"
          onCollide={(e) => {
            sounds.keep_1.play();
            if (typeof onSave === "function") onSave();
          }}
        />
        <>
          {planes.map((plane, index) => (
            <BoxCollaider
              key={index}
              position={plane[0]}
              rotation={plane[1]}
              args={plane[2]}
              mass={0}
              type="Static"
              material={{ restitution: 0.01, friction: 0.99 }}
              name="net"
              onCollide={plane[3]}
            />
          ))}
        </>
        {/* <BoxCollaider
          args={goal_area[2]}
          position={goal_area[0]}
          rotation={goal_area[1]}
          name={"goal_area"}
          onCollide={handleGoal}
        /> */}
        <mesh ref={ref}></mesh>
        <CylinderCollaider
          scale={[0.1, 0.1, 7.32]}
          args={[0.1, 0.1, 7.32]}
          position={[0, 2.9, 0.5]}
          rotation={[0, 0, Math.PI / 2]}
          mass={0}
          type="Static"
        />
        <CylinderCollaider
          args={[0.1, 0.1, 3]}
          position={[-3.66, 1.3, 0.5]}
          rotation={[0, 0, 0]}
          mass={0}
          type="Static"
          onCollide={(e) => {
            sounds.post.play();
            if (typeof onPost === "function") onPost();
          }}
        />
        <CylinderCollaider
          args={[0.1, 0.1, 3]}
          position={[3.66, 1.3, 0.5]}
          rotation={[0, 0, 0]}
          mass={0}
          type="Static"
          onCollide={(e) => {
            sounds.post.play();
            if (typeof onPost === "function") onPost();
          }}
        />
      </group>
    </group>
  );
}
