/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 stadium.gltf 
*/

import React, { useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export function Stadium(props) {
  const { nodes, materials } = useGLTF("../models/stadium/stadium.gltf");
  materials.M_gradas.emissiveIntensity = 1.8;
  materials.M_gradas.envMapIntensity = 1.8;

  // Remove the sponsor/Miami MoCAAD branding from the perimeter boards.
  const sponsorMaterial = useMemo(() => {
    const mat = materials.M_Sponsor_Low2;
    if (mat) {
      mat.map = null;
      mat.emissiveMap = null;
      mat.emissive = new THREE.Color(0x0a0a1a);
      mat.emissiveIntensity = 0.3;
      mat.color = new THREE.Color(0x141428);
      mat.metalness = 0.2;
      mat.roughness = 0.8;
      mat.needsUpdate = true;
    }
    return mat;
  }, [materials]);

  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, Math.PI]} scale={0.01}>
        <mesh
          geometry={nodes.feeld.geometry}
          material={materials.M_Field4}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.gradas.geometry}
          material={materials.M_gradas}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.puclico.geometry}
          material={materials.multidud}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.sponsor.geometry}
          material={sponsorMaterial}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.terrain.geometry}
          material={materials.M_terrain}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Mesh002.geometry}
          material={materials.M_Fishnet}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Mesh002_1.geometry}
          material={materials.M_Metal}
          castShadow
          receiveShadow
        />
      </group>
    </group>
  );
}

useGLTF.preload("../models/stadium/stadium.gltf");
